# Generated by Django 5.0.1 on 2024-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyMPvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item6_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item7_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item8_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_ret', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('acum_ret', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyMPweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item6_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item7_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item8_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_total', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='monthlyMPvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item6_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item7_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item8_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_ret', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('acum_ret', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPclsweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('cls5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cls4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cls3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cls2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cls1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('risk_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
    ]
