# Generated by Django 5.0.1 on 2024-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='astcls5_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='astcls5_l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='minRiskTol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RiskTol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
