# Generated by Django 5.0.1 on 2024-02-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_astcls1_h_portfolio_astcls1_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvUniv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('종목코드', models.CharField(blank=True, null=True)),
                ('종목명', models.CharField(blank=True, max_length=30, null=True)),
                ('시장구분', models.CharField(blank=True, null=True)),
                ('자산군', models.CharField(blank=True, null=True)),
                ('자산종류', models.CharField(blank=True, null=True)),
                ('위험도', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
