# Generated by Django 5.0.1 on 2024-02-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_invuniv_modelport'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='rskdgr_l',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
