# Generated by Django 5.0.1 on 2024-02-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_rskdgr_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelport',
            name='incept_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
