# Generated by Django 5.0.1 on 2024-02-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_modelport_portid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, null=True)),
                ('계좌번호', models.CharField(blank=True, max_length=10, null=True)),
                ('계좌명', models.CharField(blank=True, null=True)),
                ('은행코드', models.CharField(blank=True, null=True)),
                ('개설일시', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
