# Generated by Django 5.0.1 on 2024-02-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_modelport_portid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, null=True)),
                ('계좌번호', models.CharField(blank=True, max_length=10, null=True)),
                ('계좌명', models.CharField(blank=True, null=True)),
                ('은행코드', models.CharField(blank=True, null=True)),
                ('개설일시', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyMPvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item6_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item7_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item8_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_ret', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dailyMPwt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item6_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item7_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item8_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_total', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=5, null=True)),
                ('QA1', models.CharField(blank=True, max_length=5, null=True)),
                ('QA2', models.CharField(blank=True, max_length=5, null=True)),
                ('QA3', models.CharField(blank=True, max_length=5, null=True)),
                ('QA4', models.CharField(blank=True, max_length=5, null=True)),
                ('QA5', models.CharField(blank=True, max_length=5, null=True)),
                ('QA6', models.CharField(blank=True, max_length=5, null=True)),
                ('QA7', models.CharField(blank=True, max_length=5, null=True)),
                ('riskscore', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='RiskTolDesc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
