# Generated by Django 5.0.1 on 2024-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_account_dailympvalue_dailympwt_questionarie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyMPweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item2_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item3_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item4_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item5_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item6_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item7_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('item8_val', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('port_total', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dailyMPwt',
        ),
    ]
