# Generated by Django 5.0.1 on 2024-02-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=5, null=True)),
                ('QA1', models.CharField(blank=True, max_length=5, null=True)),
                ('QA2', models.CharField(blank=True, max_length=5, null=True)),
                ('QA3', models.CharField(blank=True, max_length=5, null=True)),
                ('QA4', models.CharField(blank=True, max_length=5, null=True)),
                ('QA5', models.CharField(blank=True, max_length=5, null=True)),
                ('QA6', models.CharField(blank=True, max_length=5, null=True)),
                ('QA7', models.CharField(blank=True, max_length=5, null=True)),
                ('riskscore', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
