# Generated by Django 5.0.1 on 2024-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_questionarie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='RiskTolDesc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
