# Generated by Django 5.0.1 on 2024-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_profile_risktoldesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyMPvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('port_id', models.CharField(blank=True, null=True)),
                ('item1_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item2_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item3_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item4_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item5_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item6_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item7_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item8_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('item9_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('port_val', models.DecimalField(decimal_places=6, max_digits=20)),
                ('port_ret', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
    ]
