# Generated by Django 5.0.1 on 2024-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_questionarie_riskscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarie',
            name='riskscore',
            field=models.CharField(blank=True, null=True),
        ),
    ]
