# Generated by Django 5.0.1 on 2024-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_questionarie_riskscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailympvalue',
            name='acum_ret',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
