# Generated by Django 5.0.1 on 2024-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_dailympvalue_date_alter_dailympweight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='app_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='app_secret',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='cano',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
