# Generated by Django 5.0.1 on 2024-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_account_app_key_account_app_secret_account_cano'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='portfolio_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
