# Generated by Django 5.0.1 on 2024-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_account_portfolio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sub_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sub_type_desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
