# Generated by Django 5.0.1 on 2024-05-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_portfolio_url_portfolio_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
