# Generated by Django 5.0.1 on 2024-05-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_portfolio_portfolio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
